// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("Order")]
public partial class Order
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("Order_Date", TypeName = "date")]
    public DateTime OrderDate { get; set; }

    [Column("Order_Sum")]
    public double OrderSum { get; set; }

    [Column("Urer_Id")]
    public int UrerId { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("UrerId")]
    [InverseProperty("Orders")]
    public virtual User Urer { get; set; }
}