// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("Product")]
public partial class Product
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("Category_ID")]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(15)]
    public string Name { get; set; }

    [StringLength(40)]
    public string Description { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [Column("url_image")]
    [StringLength(50)]
    public string UrlImage { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]

    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}